import React from 'react';
import {
    AngularIcon,
    CssIcon,
    DockerIcon,
    FirebaseIcon,
    GatsbyIcon,
    GitIcon,
    GraphQLIcon,
    HtmlIcon,
    JavaScriptIcon,
    MuiIcon,
    NodejsIcon,
    ReactIcon,
    StyledComponentsIcon,
    TypeScriptIcon,
    WebpackIcon,
} from '@components/icons';

export const SKILLS = [
    {
        id: 'html',
        name: 'HTML',
        Icon: <HtmlIcon />,
        color: '#E14E1D',
        url: 'https://html.spec.whatwg.org/',
    },
    {
        id: 'css',
        name: 'CSS',
        Icon: <CssIcon />,
        color: '#0277BD',
        url: 'https://www.w3.org/TR/CSS/',
    },
    {
        id: 'js',
        name: 'JavaScript',
        Icon: <JavaScriptIcon />,
        color: '#f5de19',
        url: 'https://ecma-international.org/publications-and-standards/standards/ecma-262/',
    },
    {
        id: 'ts',
        name: 'TypeScript',
        Icon: <TypeScriptIcon />,
        color: '#2f74c0',
        url: 'https://www.typescriptlang.org/',
    },
    {
        id: 'nodejs',
        name: 'Node.js',
        Icon: <NodejsIcon />,
        color: '#9dc157',
        url: 'https://nodejs.org/',
    },
    {
        id: 'react',
        name: 'React',
        Icon: <ReactIcon />,
        color: '#00D8FF',
        url: 'https://react.dev/',
    },
    {
        id: 'gatsby',
        name: 'Gatsby',
        Icon: <GatsbyIcon />,
        color: '#742abb',
        url: 'https://www.gatsbyjs.com/',
    },
    {
        id: 'angular',
        name: 'Angular',
        Icon: <AngularIcon />,
        color: '#d70230',
        url: 'https://angular.io/',
    },
    {
        id: 'graphql',
        name: 'GraphQL',
        Icon: <GraphQLIcon />,
        color: '#dd34a6',
        url: 'https://graphql.org/',
    },
    {
        id: 'git',
        name: 'Git',
        Icon: <GitIcon />,
        color: '#e94f32',
        url: 'https://git-scm.com/',
    },
    {
        id: 'webpack',
        name: 'Webpack',
        Icon: <WebpackIcon />,
        color: '#1c74bb',
        url: 'https://webpack.js.org/',
    },
    {
        id: 'firebase',
        name: 'Firebase',
        Icon: <FirebaseIcon />,
        color: '#ffcb28',
        url: 'https://firebase.google.com/',
    },
    {
        id: 'docker',
        name: 'Docker',
        Icon: <DockerIcon />,
        color: '#2d9aee',
        url: 'https://www.docker.com/',
    },
    {
        id: 'mui',
        name: 'MUI',
        Icon: <MuiIcon />,
        color: '#1083ff',
        url: 'https://mui.com/',
    },
    {
        id: 'styled-components',
        name: 'Styled-components',
        Icon: <StyledComponentsIcon />,
        color: '#de7496',
        url: 'https://styled-components.com/',
    },
];
